# Generated by Django 6.0.2 on 2026-02-21 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_add_producto_descripcion_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='codigo',
            field=models.CharField(max_length=50, unique=True, verbose_name='Código SKU'),
        ),
    ]
