# Generated by Django 6.0.2 on 2026-02-23 01:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0006_add_perfil_usuario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReporteVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(help_text='Fecha del día reportado')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20)),
                ('observaciones', models.CharField(blank=True, max_length=500)),
                ('aprobado_en', models.DateTimeField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('aprobado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reportes_aprobados', to=settings.AUTH_USER_MODEL)),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportes_venta', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reporte de venta',
                'verbose_name_plural': 'Reportes de venta',
                'ordering': ['-creado_en'],
                'unique_together': {('fecha', 'vendedor')},
            },
        ),
        migrations.CreateModel(
            name='ReporteVentaLinea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas_reporte', to='inventario.producto')),
                ('reporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas', to='inventario.reporteventa')),
            ],
            options={
                'verbose_name': 'Línea de reporte',
                'verbose_name_plural': 'Líneas de reporte',
            },
        ),
    ]
