# Generated by Cursor on 2026-04-20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0007_reporteventa_reporteventalinea'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientoinventario',
            name='creado_por',
            field=models.ForeignKey(
                blank=True,
                help_text='Usuario autenticado que registró el movimiento',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='movimientos_inventario',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]

